// <copyright file="TerjeSettingsCollection.c" author="Terje Bruoygard">
//     This repository does not provide full code of our mods need to be fully functional.
//     That's just interfaces and simple logic that may be helpful to other developers while using our mods as dependencies.
//     Modification, repackaging, distribution or any other use of the code from this file except as specified in the LICENSE.md is strictly prohibited.
//     Copyright (c) TerjeMods. All rights reserved.
// </copyright>

modded class TerjeSettingsCollection
{
	static int MEDICINE_COLORIZED_HUD_BADGES;
	static int MEDICINE_DETAILED_MEDICINE_HUD_BADGES;
	static int MEDICINE_ENABLE_MEDICAL_COMA;
	static int MEDICINE_VISCERA_ENABLED;
	static int MEDICINE_VISCERA_HEALTH_LOSE;
	static int MEDICINE_VISCERA_BLOOD_LOSE;
	static int MEDICINE_VISCERA_SYMPTON_PERIOD;
	static int MEDICINE_VISCERA_SUTURES_MIN;
	static int MEDICINE_VISCERA_SUTURES_MAX;
	static int MEDICINE_STUBS_ENABLED;
	static int MEDICINE_STUBS_HEALTH_LOSE;
	static int MEDICINE_STUBS_BLOOD_LOSE;
	static int MEDICINE_STUBS_SUTURES_MIN;
	static int MEDICINE_STUBS_SUTURES_MAX;
	static int MEDICINE_BULLETS_ENABLED;
	static int MEDICINE_BULLETS_HEALTH_LOSE;
	static int MEDICINE_BULLETS_BLOOD_LOSE;
	static int MEDICINE_BULLETS_SUTURES_MIN;
	static int MEDICINE_BULLETS_SUTURES_MAX;
	static int MEDICINE_CLEAN_BANDAGED_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_CLEAN_BANDAGED_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_BANDAGED_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_DIRTY_BANDAGED_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_BANDAGE_INFECTION_CHANCE;
	static int MEDICINE_CLEAN_TO_DIRTY_BANDAGE_TIME;
	static int MEDICINE_BANDAGED_WOUNDS_HEAL_TIME;
	static int MEDICINE_DIRTY_BANDAGE_WOUNDS_HEAL_MODIFIER;
	static int MEDICINE_SUTURES_ENABLED;
	static int MEDICINE_CLEAN_SUTURE_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_CLEAN_SUTURE_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_SUTURE_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_DIRTY_SUTURE_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_SUTURE_INFECTION_CHANCE;
	static int MEDICINE_CLEAN_TO_DIRTY_SUTURE_TIME;
	static int MEDICINE_SUTURE_WOUNDS_HEAL_TIME;
	static int MEDICINE_DIRTY_SUTURE_WOUNDS_HEAL_MODIFIER;
	static int MEDICINE_CLEAN_SUTURE_BANDAGED_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_CLEAN_SUTURE_BANDAGED_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_HEALTH_LOSE;
	static int MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_BLOOD_LOSE;
	static int MEDICINE_DIRTY_SUTURE_BANDAGED_INFECTION_CHANCE;
	static int MEDICINE_CLEAN_TO_DIRTY_SUTURE_BANDAGED_TIME;
	static int MEDICINE_SUTURE_BANDAGED_WOUNDS_HEAL_TIME;
	static int MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_HEAL_MODIFIER;
	static int MEDICINE_BANDAGING_SEPSIS_CHANCE_D_H;
	static int MEDICINE_BANDAGING_SEPSIS_CHANCE_D_G;
	static int MEDICINE_BANDAGING_SEPSIS_MODIFIER;
	static int MEDICINE_SURGERY_SEPSIS_CHANCE_D_H;
	static int MEDICINE_SURGERY_SEPSIS_CHANCE_D_G;
	static int MEDICINE_SURGERY_SEPSIS_MODIFIER;
	static int MEDICINE_WATER_DRAIN_FROM_VOMIT;
	static int MEDICINE_ENERGY_DRAIN_FROM_VOMIT;
	static int MEDICINE_LIGHT_BLEED_MODIFIER;
	static int MEDICINE_BLOOD_REGEN_COMMON_MODIFIER;
	static int MEDICINE_BLOOD_REGEN_MEDS_MODIFIER;
	static int MEDICINE_WATER_LOW_DAMAGE_MODIFIER;
	static int MEDICINE_ENERGY_LOW_DAMAGE_MODIFIER;
	static int MEDICINE_HEALTH_REGEN_COMMON_MODIFIER;
	static int MEDICINE_METABOLIC_SPEED_ENERGY_MODIFIER;
	static int MEDICINE_METABOLIC_SPEED_WATER_MODIFIER;
	static int MEDICINE_HANDS_DISINFECTION_TIME;
	static int MEDICINE_GLOVES_DISINFECTION_TIME;
	static int MEDICINE_DIRTY_SYRINGE_SEPSIS_CHANCE;
	static int MEDICINE_SLEEPING_DEC_PER_SEC_COMMON;
	static int MEDICINE_SLEEPING_DEC_PER_SEC_RADIATION;
	static int MEDICINE_SLEEPING_INC_COMMON;
	static int MEDICINE_SLEEPING_INC_COMFORT;
	static int MEDICINE_SLEEPING_HEALTH_INC;
	static int MEDICINE_SLEEPING_HEALTH_DEC;
	static int MEDICINE_MIND_DEGRADATION_MODIFIER;
	static int MEDICINE_MIND_RESTORE_COMMON_PER_SEC;
	static int MEDICINE_MIND_RESTORE_MEDS_PER_SEC;
	static int MEDICINE_MIND_CRITICAL_DAMAGE;
	static int MEDICINE_MIND_TRANSFER_AGENTS_MODIFIER;
	static int MEDICINE_MIND_USE_LAUGHTER_SYMPTOM;
	static int MEDICINE_PAIN_ENABLED;
	static int MEDICINE_PAIN_DEC_LEVEL0;
	static int MEDICINE_PAIN_DEC_LEVEL1;
	static int MEDICINE_PAIN_DEC_LEVEL2;
	static int MEDICINE_PAIN_DEC_LEVEL3;
	static int MEDICINE_PAIN_LEVEL3_UNCOUNCION_CHANCE;
	static int MEDICINE_PAIN_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_PAIN_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_SEPSIS_ENABLED;
	static int MEDICINE_BEAR_TRAP_SEPSIS_CHANCE;
	static int MEDICINE_BARBED_WIRE_SEPSIS_CHANCE;
	static int MEDICINE_SEPSIS_INC_PER_SEC;
	static int MEDICINE_SEPSIS_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_SEPSIS_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_SEPSIS_CRITICAL_SYMPTOM_CHANCE;
	static int MEDICINE_SEPSIS_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_SEPSIS_DEC_PER_SEC;
	static int MEDICINE_Z_VIRUS_ENABLED;
	static int MEDICINE_Z_VIRUS_INC_PER_SEC;
	static int MEDICINE_Z_VIRUS_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_Z_VIRUS_DEC_PER_SEC;
	static int MEDICINE_Z_VIRUS_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_Z_VIRUS_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_Z_VIRUS_CRITICAL_SYMPTOM_CHANCE;
	static int MEDICINE_Z_VIRUS_VOMIT_FORCE_MODIFIER;
	static int MEDICINE_RADIATION_ENABLED;
	static int MEDICINE_RADIATION_COMMON_DEC_PER_SEC;
	static int MEDICINE_RADIATION_MEDS_DEC_PER_SEC;
	static int MEDICINE_RADIATION_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_RADIATION_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_RADIATION_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_RADIATION_VOMIT_FORCE_MODIFIER;
	static int MEDICINE_RADIATION_TRANSFER_PER_SEC;
	static int MEDICINE_RADIATION_TRANSFER_MOD;
	static int MEDICINE_RADIATION_TRANSFER_GEAR;
	static int MEDICINE_POSION_ENABLED;
	static int MEDICINE_POISON_DEC_PER_SEC;
	static int MEDICINE_POISON_ANTIDOTE_HEAL_MULTIPLIER;
	static int MEDICINE_POISON_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_POISON_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_POISON_CRITICAL_SYMPTOM_CHANCE;
	static int MEDICINE_POISON_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_POISON_VOMIT_FORCE_MODIFIER;
	static int MEDICINE_POISON_TRANSFER_AGENTS_MODIFIER;
	static int MEDICINE_BIOHAZARD_ENABLED;
	static int MEDICINE_BIOHAZARD_SKIN_IRRITATION;
	static int MEDICINE_BIOHAZARD_REQUIRED_ONLY_GAS_MASK;
	static int MEDICINE_BIOHAZARD_DEC_PER_SEC;
	static int MEDICINE_BIOHAZARD_ANTIDOTE_HEAL_MULTIPLIER;
	static int MEDICINE_BIOHAZARD_SYMPTOM_CHANCE;
	static int MEDICINE_BIOHAZARD_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_BIOHAZARD_VOMIT_FORCE_MODIFIER;
	static int MEDICINE_BIOHAZARD_TRANSFER_AGENTS_MODIFIER;
	static int MEDICINE_RABIES_ENABLED;
	static int MEDICINE_RABIES_WOLF_INFECTED_CHANCE;
	static int MEDICINE_RABIES_INC_PER_SEC;
	static int MEDICINE_RABIES_DEC_PER_SEC;
	static int MEDICINE_RABIES_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_RABIES_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_RABIES_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_RABIES_CRITICAL_SYMPTOM_CHANCE;
	static int MEDICINE_RABIES_BODY_TEMPERATURE_MODIFIER;
	static int MEDICINE_BURN_ENABLED;
	static int MEDICINE_FROSTBITE_ENABLED;
	static int MEDICINE_INFLUENZA_ENABLED;
	static int MEDICINE_INFLUENZA_INC_PER_SEC;
	static int MEDICINE_INFLUENZA_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_INFLUENZA_DEC_PER_SEC;
	static int MEDICINE_INFLUENZA_LIGHT_SYMPTOM_CHANCE;
	static int MEDICINE_INFLUENZA_HEAVY_SYMPTOM_CHANCE;
	static int MEDICINE_INFLUENZA_CRITICAL_SYMPTOM_CHANCE;
	static int MEDICINE_INFLUENZA_BODY_TEMPERATURE_MODIFIER;
	static int MEDICINE_INFLUENZA_DEFAULT_IMMUNITY_STRENGTH;
	static int MEDICINE_INFLUENZA_TRANSFER_AGENTS_MODIFIER;
	static int MEDICINE_INFLUENZA_IMMUNITY_HEAL_THRESHOLD;
	static int MEDICINE_INFLUENZA_TEMPERATURE_WARN_MODIFIER;
	static int MEDICINE_INFLUENZA_TEMPERATURE_CRIT_MODIFIER;
	static int MEDICINE_INFLUENZA_TEMPERATURE_EMPTY_MODIFIER;
	static int MEDICINE_OVERDOSE_ENABLED;
	static int MEDICINE_OVERDOSE_DEC_PER_SEC;
	static int MEDICINE_OVERDOSE_UNCONSCIOUS_CHANCE;
	static int MEDICINE_OVERDOSE_CRITICAL_DMG_MULTIPLIER;
	static int MEDICINE_CONTUSION_ENABLED;
	static int MEDICINE_CONTUSION_DEC_PER_SEC;
	static int MEDICINE_CONTUSION_UNCONSCIOUS_CHANCE;
	static int MEDICINE_CONTUSION_HEAL_MODIFIER;
	static int MEDICINE_HEMATOMAS_ENABLED;
	static int MEDICINE_HEMATOMAS_HEAL_COMMON_MODIFIER;
	static int MEDICINE_HEMATOMAS_HEAL_MEDS_MODIFIER;
	static int MEDICINE_HEMATOMAS_CRITICAL_COUNT;
	static int MEDICINE_HEMATOMAS_CRITICAL_DAMAGE;
	static int MEDICINE_MELEE_DAMMAGE_PLAYER_IN_BLOCK;
	static int MEDICINE_MELEE_DAMMAGE_NO_STAMINA;
	static int MEDICINE_MELEE_DAMMAGE_CONTUSION_CHANCE;
	static int MEDICINE_MELEE_DAMMAGE_STUB_WOUND_CHANCE;
	static int MEDICINE_MELEE_DAMMAGE_VISCERA_CHANCE;
	static int MEDICINE_MELEE_DAMMAGE_SEPSIS_CHANCE;
	static int MEDICINE_MELEE_DAMMAGE_HEMATOMA_CHANCE;
	static int MEDICINE_MELEE_DAMMAGE_PAIN_MIN;
	static int MEDICINE_MELEE_DAMMAGE_PAIN_MAX;
	static int MEDICINE_MELEE_DAMMAGE_PAIN_STUB;
	static int MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_SPEED_MOD;
	static int MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_CALIBER_MOD;
	static int MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_WEIGHT_MOD;
	static int MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_A_P_MOD;
	static int MEDICINE_FIREARM_ARMOR_MODIFIER;
	static int MEDICINE_FIREARM_DAMMAGE_CONTUSION_CHANCE;
	static int MEDICINE_FIREARM_DAMMAGE_VISCERA_CHANCE;
	static int MEDICINE_FIREARM_BULLET_THROUGH_CHANCE;
	static int MEDICINE_FIREARM_DAMMAGE_SEPSIS_CHANCE;
	static int MEDICINE_FIREARM_DAMMAGE_PAIN_STUB;
	static int MEDICINE_FIREARM_DAMMAGE_PAIN_BULLET;
	static int MEDICINE_FIREARM_DAMMAGE_PAIN_STOPPED;
	static int MEDICINE_ZOMBIE_ATTACK_MIND_DEGRADATION_VALUE;
	static int MEDICINE_ZOMBIE_ATTACK_MIND_DEGRADATION_TIME;
	static int MEDICINE_ZOMBIE_DAMMAGE_PLAYER_IN_BLOCK;
	static int MEDICINE_ZOMBIE_DAMMAGE_NO_STAMINA;
	static int MEDICINE_ZOMBIE_DAMMAGE_HEMATOMA_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_BLEED_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_CONTUSION_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_STUB_WOUND_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_HEMATOMA_VIRUS_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_BLEED_VIRUS_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_STUB_WOUND_VIRUS_CHANCE;
	static int MEDICINE_ZOMBIE_DAMMAGE_PAIN_MIN;
	static int MEDICINE_ZOMBIE_DAMMAGE_PAIN_MAX;
	static int MEDICINE_ZOMBIE_DAMMAGE_PAIN_STUB;
	static int MEDICINE_IMMUNITY_BIOHAZARD_EXP_GAIN;
	static int MEDICINE_IMMUNITY_CONTUSION_EXP_GAIN;
	static int MEDICINE_IMMUNITY_HEMATOMA_EXP_GAIN;
	static int MEDICINE_IMMUNITY_INFLUENZA_EXP_GAIN;
	static int MEDICINE_IMMUNITY_PAIN_EXP_GAIN;
	static int MEDICINE_IMMUNITY_POISON_EXP_GAIN;
	static int MEDICINE_IMMUNITY_RADIATION_EXP_GAIN;
	static int MEDICINE_IMMUNITY_SEPSIS_EXP_GAIN;
	static int MEDICINE_IMMUNITY_ZOMBIE_EXP_GAIN;
	static int MEDICINE_IMMUNITY_RABIES_EXP_GAIN;
	static int MEDICINE_MEDICINE_BANDAGE_EXP_GAIN;
	static int MEDICINE_MEDICINE_STUB_SURGERY_EXP_GAIN;
	static int MEDICINE_MEDICINE_BULLET_SURGERY_EXP_GAIN;
	static int MEDICINE_MEDICINE_VISCERA_SURGERY_EXP_GAIN;
	static int MEDICINE_PSIONIC_AREAS_POWER_MOD;
	static int MEDICINE_RADIOACTIVE_AREAS_POWER_MOD;
	static int MEDICINE_RADIATION_DAMAGE_ZOMBIES;
	static int MEDICINE_RADIATION_DAMAGE_ANIMALS;
	static int MEDICINE_RADIATION_DO_ITEMS_ACCUMULATE;
	static int MEDICINE_RADIATION_DO_VEHICLES_ACCUMULATE;
	static int MEDICINE_RADIATION_TRANSFER_WITH_PARENT;
	static int MEDICINE_RADIATION_ITEM_LOSE_PER_SEC;
	static int MEDICINE_VISCERA_FAILED_HEALTH_LOSE;
	static int MEDICINE_VISCERA_FAILED_BLOOD_LOSE;
	static int MEDICINE_STUBS_FAILED_HEALTH_LOSE;
	static int MEDICINE_STUBS_FAILED_BLOOD_LOSE;
	static int MEDICINE_BULLETS_FAILED_HEALTH_LOSE;
	static int MEDICINE_BULLETS_FAILED_BLOOD_LOSE;

	override void OnInit()
	{
		super.OnInit();
		RegisterRegion("Medicine", "General settings");
		MEDICINE_COLORIZED_HUD_BADGES = RegisterSettingBool("Medicine.ColorizedHudBadges", "Medicine", "Badges on the status bar will have different colors depending on the severity level to make it easier to identify illnesses.", true, false);
		MEDICINE_DETAILED_MEDICINE_HUD_BADGES = RegisterSettingBool("Medicine.DetailedMedicineHudBadges", "Medicine", "When this option is enabled, players will see separate icons for each medical drug that affects them (for casual servers). When this option is disabled, players will see the standard pill icon when any medical drug affects their body (for hardcore servers).", false, false);
		MEDICINE_ENABLE_MEDICAL_COMA = RegisterSettingBool("Medicine.EnableMedicalComa", "Medicine", "When health or blood is critically low, the player falls into a coma. He can survive and out it only if another player can raise his blood and health indicators above the critical level.", true, true);
		
		RegisterRegion("Medicine", "Viscera (internal organs wound) settings");
		MEDICINE_VISCERA_ENABLED = RegisterSettingBool("Medicine.VisceraEnabled", "Medicine", "The parameter determines whether viscera wound is enabled on the server or not.", true, true);
		MEDICINE_VISCERA_HEALTH_LOSE = RegisterSettingFloat("Medicine.VisceraHealthLose", "Medicine", "The amount of health that a player loses every second when viscera (internal organs) are damaged.", 0.1, true);
		MEDICINE_VISCERA_BLOOD_LOSE = RegisterSettingFloat("Medicine.VisceraBloodLose", "Medicine", "The amount of blood that a player loses every second when viscera (internal organs) are damaged.", 2.0, true);
		MEDICINE_VISCERA_SYMPTON_PERIOD = RegisterSettingFloat("Medicine.VisceraSymptonPeriod", "Medicine", "The period of time inseconds between symptoms of bloody cough due to damage to internal organs.", 2.5, true);
		MEDICINE_VISCERA_SUTURES_MIN = RegisterSettingInt("Medicine.VisceraSuturesMin", "Medicine", "How many sutures will a player have after internal surgery (Minumum integer number).", 1, true);
		MEDICINE_VISCERA_SUTURES_MAX = RegisterSettingInt("Medicine.VisceraSuturesMax", "Medicine", "How many sutures will a player have after internal surgery (Maximum integer number).", 3, true);
		MEDICINE_VISCERA_FAILED_HEALTH_LOSE = RegisterSettingFloat("Medicine.VisceraSurgFailedHealthLose", "Medicine", "The amount of health that a player lose after failed surgery operation on viscera (internal organs).", 10, true);
		MEDICINE_VISCERA_FAILED_BLOOD_LOSE = RegisterSettingFloat("Medicine.VisceraSurgFailedBloodLose", "Medicine", "The amount of blood that a player lose after failed surgery operation on viscera (internal organs).", 200, true);
		
		RegisterRegion("Medicine", "Stubs (wounds with heavy bleeding) settings");
		MEDICINE_STUBS_ENABLED = RegisterSettingBool("Medicine.StubsEnabled", "Medicine", "The parameter determines whether stub wounds is enabled on the server or not.", true, true);
		MEDICINE_STUBS_HEALTH_LOSE = RegisterSettingFloat("Medicine.StubsHealthLose", "Medicine", "The amount of health that a player loses every second when has heavy bleed (stub wounds).", 0.01, true);
		MEDICINE_STUBS_BLOOD_LOSE = RegisterSettingFloat("Medicine.StubsBloodLose", "Medicine", "The amount of blood that a player loses every second when has heavy bleed (stub wounds).", 4.0, true);
		MEDICINE_STUBS_SUTURES_MIN = RegisterSettingInt("Medicine.StubsSuturesMin", "Medicine", "How many sutures will a player have after stub surgery (Minumum integer number).", 1, true);
		MEDICINE_STUBS_SUTURES_MAX = RegisterSettingInt("Medicine.StubsSuturesMax", "Medicine", "How many sutures will a player have after stub surgery (Maximum integer number).", 1, true);
		MEDICINE_STUBS_FAILED_HEALTH_LOSE = RegisterSettingFloat("Medicine.StubsSurgFailedHealthLose", "Medicine", "The amount of health that a player lose after failed stub surgery.", 0, true);
		MEDICINE_STUBS_FAILED_BLOOD_LOSE = RegisterSettingFloat("Medicine.StubsSurgFailedBloodLose", "Medicine", "The amount of blood that a player lose after failed stub surgery.", 0, true);
		
		RegisterRegion("Medicine", "Bullets (wounds with bullets inside the body) settings");
		MEDICINE_BULLETS_ENABLED = RegisterSettingBool("Medicine.BulletsEnabled", "Medicine", "The parameter determines whether bullet wounds is enabled on the server or not.", true, true);
		MEDICINE_BULLETS_HEALTH_LOSE = RegisterSettingFloat("Medicine.BulletsHealthLose", "Medicine", "The amount of health that a player loses every second when has bullet inside the body.", 0.01, true);
		MEDICINE_BULLETS_BLOOD_LOSE = RegisterSettingFloat("Medicine.BulletsBloodLose", "Medicine", "The amount of blood that a player loses every second when has bullet inside the body.", 0.5, true);
		MEDICINE_BULLETS_SUTURES_MIN = RegisterSettingInt("Medicine.BulletsSuturesMin", "Medicine", "How many sutures will a player have after bullet remove surgery if stub is closed (Minumum integer number).", 1, true);
		MEDICINE_BULLETS_SUTURES_MAX = RegisterSettingInt("Medicine.BulletsSuturesMax", "Medicine", "How many sutures will a player have after bullet remove surgery if stub is closed (Maximum integer number).", 1, true);
		MEDICINE_BULLETS_FAILED_HEALTH_LOSE = RegisterSettingFloat("Medicine.BulletsSurgFailedHealthLose", "Medicine", "The amount of health that a player lose after failed bullet remove surgery.", 0, true);
		MEDICINE_BULLETS_FAILED_BLOOD_LOSE = RegisterSettingFloat("Medicine.BulletsSurgFailedBloodLose", "Medicine", "The amount of blood that a player lose after failed bullet remove surgery.", 100, true);
		
		RegisterRegion("Medicine", "Bandages (common) settings");
		MEDICINE_CLEAN_BANDAGED_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.CleanBandagedWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has clean bandaged wounds.", 0.0, true);
		MEDICINE_CLEAN_BANDAGED_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.CleanBandagedWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has clean bandaged wounds.", 0.25, true);
		MEDICINE_DIRTY_BANDAGED_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.DirtyBandagedWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has dirty bandaged wounds.", 0.04, true);
		MEDICINE_DIRTY_BANDAGED_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.DirtyBandagedWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has dirty bandaged wounds.", 0.5, true);
		MEDICINE_DIRTY_BANDAGE_INFECTION_CHANCE = RegisterSettingFloat("Medicine.DirtyBandageInfectionChance", "Medicine", "The chance of infection from a dirty bandage in the wound.", 0.005, true);
		MEDICINE_CLEAN_TO_DIRTY_BANDAGE_TIME = RegisterSettingFloat("Medicine.CleanToDirtyBandageTime", "Medicine", "The time in seconds it takes for a bandage to become dirty. Use 0 to disable dirty bandages.", 1000, true);
		MEDICINE_BANDAGED_WOUNDS_HEAL_TIME = RegisterSettingFloat("Medicine.BandagedWoundsHealTime", "Medicine", "The time in seconds it takes for a bandaged wound to automatically heal.", 2700, true);
		MEDICINE_DIRTY_BANDAGE_WOUNDS_HEAL_MODIFIER = RegisterSettingFloat("Medicine.DirtyBandageWoundsHealModifier", "Medicine", "A modifier that affects the healing time of a wound with a dirty bandage.", 0.25, true);
		
		RegisterRegion("Medicine", "Sutures (common) settings");
		MEDICINE_SUTURES_ENABLED = RegisterSettingBool("Medicine.SuturesEnabled", "Medicine", "The parameter determines whether sutures is enabled on the server or not.", true, true);
		MEDICINE_CLEAN_SUTURE_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.CleanSutureWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has clean suture wounds.", 0.0, true);
		MEDICINE_CLEAN_SUTURE_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.CleanSutureWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has clean suture wounds.", 0.0, true);
		MEDICINE_DIRTY_SUTURE_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.DirtySutureWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has dirty suture wounds.", 0.01, true);
		MEDICINE_DIRTY_SUTURE_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.DirtySutureWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has dirty suture wounds.", 0.0, true);
		MEDICINE_DIRTY_SUTURE_INFECTION_CHANCE = RegisterSettingFloat("Medicine.DirtySutureInfectionChance", "Medicine", "The chance of infection from a dirty suture in the wound.", 0.01, true);
		MEDICINE_CLEAN_TO_DIRTY_SUTURE_TIME = RegisterSettingFloat("Medicine.CleanToDirtySutureTime", "Medicine", "The time in seconds it takes for a suture to become dirty. Use 0 to disable dirty sutures.", 300, true);
		MEDICINE_SUTURE_WOUNDS_HEAL_TIME = RegisterSettingFloat("Medicine.SutureWoundsHealTime", "Medicine", "The time in seconds it takes for a suture wound to automatically heal.", 1800, true);
		MEDICINE_DIRTY_SUTURE_WOUNDS_HEAL_MODIFIER = RegisterSettingFloat("Medicine.DirtySutureWoundsHealModifier", "Medicine", "A modifier that affects the healing time of a wound with a dirty suture.", 0.25, true);

		RegisterRegion("Medicine", "Sutures (bandaged) settings");
		MEDICINE_CLEAN_SUTURE_BANDAGED_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.CleanSutureBandagedWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has clean bandaged suture wounds.", 0.0, true);
		MEDICINE_CLEAN_SUTURE_BANDAGED_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.CleanSutureBandagedWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has clean bandaged suture wounds.", 0.0, true);
		MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_HEALTH_LOSE = RegisterSettingFloat("Medicine.DirtySutureBandagedWoundsHealthLose", "Medicine", "The amount of health that a player loses every second when has dirty bandaged suture wounds.", 0.005, true);
		MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_BLOOD_LOSE = RegisterSettingFloat("Medicine.DirtySutureBandagedWoundsBloodLose", "Medicine", "The amount of blood that a player loses every second when has dirty bandaged suture wounds.", 0.0, true);
		MEDICINE_DIRTY_SUTURE_BANDAGED_INFECTION_CHANCE = RegisterSettingFloat("Medicine.DirtySutureBandagedInfectionChance", "Medicine", "The chance of infection from a dirty bandaged suture in the wound.", 0.005, true);
		MEDICINE_CLEAN_TO_DIRTY_SUTURE_BANDAGED_TIME = RegisterSettingFloat("Medicine.CleanToDirtySutureBandagedTime", "Medicine", "The time in seconds it takes for a bandaged suture to become dirty. Use 0 to disable dirty bandaged sutures.", 600, true);
		MEDICINE_SUTURE_BANDAGED_WOUNDS_HEAL_TIME = RegisterSettingFloat("Medicine.SutureBandagedWoundsHealTime", "Medicine", "The time in seconds it takes for a bandaged suture wound to automatically heal.", 900, true);
		MEDICINE_DIRTY_SUTURE_BANDAGED_WOUNDS_HEAL_MODIFIER = RegisterSettingFloat("Medicine.DirtySutureBandagedWoundsHealModifier", "Medicine", "A modifier that affects the healing time of a wound with a dirty bandaged suture.", 0.5, true);

		RegisterRegion("Medicine", "Infection chance settings when bandaging");
		MEDICINE_BANDAGING_SEPSIS_CHANCE_D_H = RegisterSettingFloat("Medicine.BandagingSepsisChanceDH", "Medicine", "There is a chance of getting sepsis when applying bandages to a wound with dirty hands.", 0.25, true);
		MEDICINE_BANDAGING_SEPSIS_CHANCE_D_G = RegisterSettingFloat("Medicine.BandagingSepsisChanceDG", "Medicine", "There is a chance of getting sepsis when applying bandages to a wound with non-disinfected gloves.", 0.15, true);
		MEDICINE_BANDAGING_SEPSIS_MODIFIER = RegisterSettingFloat("Medicine.BandagingSepsisModifier", "Medicine", "There is a general modifier for GetInfectionChance function from ItemBase for bandaging actions.", 1.0, true);
		
		RegisterRegion("Medicine", "Infection chance settings when surgery");
		MEDICINE_SURGERY_SEPSIS_CHANCE_D_H = RegisterSettingFloat("Medicine.SurgerySepsisChanceDH", "Medicine", "There is a chance of getting sepsis when applying bandages to a wound with non-disinfected hands.", 0.8, true);
		MEDICINE_SURGERY_SEPSIS_CHANCE_D_G = RegisterSettingFloat("Medicine.SurgerySepsisChanceDG", "Medicine", "There is a chance of getting sepsis when applying bandages to a wound with non-disinfected gloves.", 0.8, true);
		MEDICINE_SURGERY_SEPSIS_MODIFIER = RegisterSettingFloat("Medicine.SurgerySepsisModifier", "Medicine", "There is a general modifier for GetInfectionChance function from ItemBase for surgery actions", 1.0, true);
		
		RegisterRegion("Medicine", "Metabolism settings");
		MEDICINE_WATER_DRAIN_FROM_VOMIT = RegisterSettingFloat("Medicine.WaterDrainFromVomit", "Medicine", "The value of water units that a player will lose when vomiting.", 70, true);
		MEDICINE_ENERGY_DRAIN_FROM_VOMIT = RegisterSettingFloat("Medicine.EnergyDrainFromVomit", "Medicine", "The value of energy units that a player will lose when vomiting.", 55, true);
		MEDICINE_LIGHT_BLEED_MODIFIER = RegisterSettingFloat("Medicine.LightBleedModifier", "Medicine", "Modifier responsible for the intensity of light bleeding (vanilla cut).", 0.25, true);
		MEDICINE_BLOOD_REGEN_COMMON_MODIFIER = RegisterSettingFloat("Medicine.BloodRegenCommonModifier", "Medicine", "Modifier responsible for the intensity of common blood regeneration (without drugs).", 0.1, true);
		MEDICINE_BLOOD_REGEN_MEDS_MODIFIER = RegisterSettingFloat("Medicine.BloodRegenMedsModifier", "Medicine", "Modifier responsible for the intensity of blood regeneration caused by medical drugs.", 1, true);
		MEDICINE_WATER_LOW_DAMAGE_MODIFIER = RegisterSettingFloat("Medicine.WaterLowDamageModifier", "Medicine", "Modifier responsible for the intensity of health damage when level of water is low.", 0.2, true);
		MEDICINE_ENERGY_LOW_DAMAGE_MODIFIER = RegisterSettingFloat("Medicine.EnergyLowDamageModifier", "Medicine", "Modifier responsible for the intensity of health damage when level of energy is low.", 0.2, true);
		MEDICINE_HEALTH_REGEN_COMMON_MODIFIER = RegisterSettingFloat("Medicine.HealthRegenCommonModifier", "Medicine", "Modifier responsible for the intensity of common health regeneration.", 0.1, true);	
		MEDICINE_METABOLIC_SPEED_ENERGY_MODIFIER = RegisterSettingFloat("Medicine.MetabolicSpeedEnergyModifier", "Medicine", "Modifier responsible for the intensity of metabolism speed energy drain.", 0.5, true);
		MEDICINE_METABOLIC_SPEED_WATER_MODIFIER = RegisterSettingFloat("Medicine.MetabolicSpeedWaterModifier", "Medicine", "Modifier responsible for the intensity of metabolism speed water drain.", 0.5, true);
		MEDICINE_HANDS_DISINFECTION_TIME = RegisterSettingFloat("Medicine.HandsDisinfectionTime", "Medicine", "How long will the player's hands remain sanitized in seconds after disinfection.", 180, true);
		MEDICINE_GLOVES_DISINFECTION_TIME = RegisterSettingFloat("Medicine.GlovesDisinfectionTime", "Medicine", "How long will the player's gloves remain sanitized in seconds after disinfection.", 300, true);
		MEDICINE_DIRTY_SYRINGE_SEPSIS_CHANCE = RegisterSettingFloat("Medicine.DirtySyringeSepsisChance", "Medicine", "Chance of infection when using a dirty syringe. Value from 0 to 1.", 0.2, true);
		
		RegisterRegion("Medicine", "Sleeping settings");
		MEDICINE_SLEEPING_DEC_PER_SEC_COMMON = RegisterSettingFloat("Medicine.SleepingDecPerSecCommon", "Medicine", "The number of sleep units that a player loses per 1 second of wakefulness.", 1.0, true);
		MEDICINE_SLEEPING_DEC_PER_SEC_RADIATION = RegisterSettingFloat("Medicine.SleepingDecPerSecRadiation", "Medicine", "The number of sleep units that a player loses per 1 second with radiation sickness.", 5.0, true);
		MEDICINE_SLEEPING_INC_COMMON = RegisterSettingFloat("Medicine.SleepingIncCommon", "Medicine", "The number of sleep units that a player receives per 1 second when sleeping in common place.", 10.0, true);
		MEDICINE_SLEEPING_INC_COMFORT = RegisterSettingFloat("Medicine.SleepingIncComfort", "Medicine", "The number of sleep units that a player receives per 1 second when sleeping in comfort place.", 25.0, true);
		MEDICINE_SLEEPING_HEALTH_INC = RegisterSettingFloat("Medicine.SleepingHealthInc", "Medicine", "The number of health units that a player receives per 1 second when sleeping in comfort place.", 0.25, true);
		MEDICINE_SLEEPING_HEALTH_DEC = RegisterSettingFloat("Medicine.SleepingHealthDec", "Medicine", "The number of health units that a player looses per 1 second when sleeping state is critical.", 0.5, true);
		
		RegisterRegion("Medicine", "Mind (mental condition) settings");
		MEDICINE_MIND_DEGRADATION_MODIFIER = RegisterSettingFloat("Medicine.MindDegradationModifier", "Medicine", "Mental degradation modifier from any mental damage sources.", 1.0, true);
		MEDICINE_MIND_RESTORE_COMMON_PER_SEC = RegisterSettingFloat("Medicine.MindRestoreCommonPerSec", "Medicine", "Mental health restore value per second without drugs.", 0.005, true);
		MEDICINE_MIND_RESTORE_MEDS_PER_SEC = RegisterSettingFloat("Medicine.MindRestoreMedsPerSec", "Medicine", "Mental health restore value per second with drugs.", 0.02, true);
		MEDICINE_MIND_CRITICAL_DAMAGE = RegisterSettingFloat("Medicine.MindCriticalDamage", "Medicine", "Damage to player health per second when mental health is critical low.", 0.1, true);
		MEDICINE_MIND_TRANSFER_AGENTS_MODIFIER = RegisterSettingFloat("Medicine.MindTransferAgentsModifier", "Medicine", "A modifier responsible for converting classic brain agents into agents of the Terje medicine system.", 0.25, true);
		MEDICINE_MIND_USE_LAUGHTER_SYMPTOM = RegisterSettingBool("Medicine.MindUseLaughterSymptom", "Medicine", "Use the laughter symptom when player's sanity (mind) is low.", true, true);		
		
		RegisterRegion("Medicine", "Pain settings");
		MEDICINE_PAIN_ENABLED = RegisterSettingBool("Medicine.PainEnabled", "Medicine", "The parameter determines whether pain is enabled on the server or not.", true, true);
		MEDICINE_PAIN_DEC_LEVEL0 = RegisterSettingFloat("Medicine.PainDecLevel0", "Medicine", "Determines the value will pain decrease at level 1 per second.", 0.006, true);
		MEDICINE_PAIN_DEC_LEVEL1 = RegisterSettingFloat("Medicine.PainDecLevel1", "Medicine", "Determines the value will pain decrease at level 1 per second.", 0.005, true);
		MEDICINE_PAIN_DEC_LEVEL2 = RegisterSettingFloat("Medicine.PainDecLevel2", "Medicine", "Determines the value will pain decrease at level 1 per second.", 0.002, true);
		MEDICINE_PAIN_DEC_LEVEL3 = RegisterSettingFloat("Medicine.PainDecLevel3", "Medicine", "Determines the value will pain decrease at level 1 per second.", 0.001, true);
		MEDICINE_PAIN_LEVEL3_UNCOUNCION_CHANCE = RegisterSettingFloat("Medicine.PainLevel3UncouncionChance", "Medicine", "Chance to go to uncouncion with level 3 pain per second. Value from 0 to 1.", 0.005, true);	
		MEDICINE_PAIN_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.PainLightSymptomChance", "Medicine", "Chance to make light pain symptoh. Value from 0 to 1.", 0.03, true);
		MEDICINE_PAIN_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.PainHeavySymptomChance", "Medicine", "Chance to make heavy pain symptoh. Value from 0 to 1.", 0.05, true);
		
		RegisterRegion("Medicine", "Sepsis (blood poisoning) settings");
		MEDICINE_SEPSIS_ENABLED = RegisterSettingBool("Medicine.SepsisEnabled", "Medicine", "The parameter determines whether sepsis is enabled on the server or not.", true, true);
		MEDICINE_BEAR_TRAP_SEPSIS_CHANCE = RegisterSettingFloat("Medicine.BearTrapSepsisChance", "Medicine", "Chance of receiving a sepsis when player take a dammage from a bear trap. Value from 0 to 1.", 0.2, true);
		MEDICINE_BARBED_WIRE_SEPSIS_CHANCE = RegisterSettingFloat("Medicine.BarbedWireSepsisChance", "Medicine", "Chance of receiving a sepsis when player take a dammage from a barbed wire. Value from 0 to 1.", 0.01, true);
		MEDICINE_SEPSIS_INC_PER_SEC = RegisterSettingFloat("Medicine.SepsisIncPerSec", "Medicine", "The number of sepsis agents the player receives every second when infected.", 0.001, true);
		MEDICINE_SEPSIS_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.SepsisLightSymptomChance", "Medicine", "Chance to make light (level 1) sepsis symptoh. Value from 0 to 1.", 0.01, true);
		MEDICINE_SEPSIS_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.SepsisHeavySymptomChance", "Medicine", "Chance to make heavy (level 2) sepsis symptoh. Value from 0 to 1.", 0.03, true);
		MEDICINE_SEPSIS_CRITICAL_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.SepsisCriticalSymptomChance", "Medicine", "Chance to make critical (level 3) sepsis symptoh. Value from 0 to 1.", 0.02, true);
		MEDICINE_SEPSIS_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.SepsisCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of sepsis.", 1.0, true);
		MEDICINE_SEPSIS_DEC_PER_SEC = RegisterSettingFloat("Medicine.SepsisDecPerSec", "Medicine", "The number of sepsis agents the player loses when has effect from antibiotics.", 0.01, true);
		
		RegisterRegion("Medicine", "Zombie virus settings");
		MEDICINE_Z_VIRUS_ENABLED = RegisterSettingBool("Medicine.ZVirusEnabled", "Medicine", "The parameter determines whether zombie virus is enabled on the server or not.", true, true);
		MEDICINE_Z_VIRUS_INC_PER_SEC = RegisterSettingFloat("Medicine.ZVirusIncPerSec", "Medicine", "The number of zombie virus agents the player receives every second when infected.", 0.001, true);
		MEDICINE_Z_VIRUS_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.ZVirusCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of zombie virus.", 2.0, true);
		MEDICINE_Z_VIRUS_DEC_PER_SEC = RegisterSettingFloat("Medicine.ZVirusDecPerSec", "Medicine", "The number of zombie virus agents the player loses when has effect from antidot.", 0.01, true);
		MEDICINE_Z_VIRUS_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.ZVirusLightSymptomChance", "Medicine", "Chance to make light (level 1) zombie virus symptoh. Value from 0 to 1.", 0.004, true);
		MEDICINE_Z_VIRUS_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.ZVirusHeavySymptomChance", "Medicine", "Chance to make heavy (level 2) zombie virus symptoh. Value from 0 to 1.", 0.015, true);
		MEDICINE_Z_VIRUS_CRITICAL_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.ZVirusCriticalSymptomChance", "Medicine", "Chance to make critical (level 3) zombie virus symptoh. Value from 0 to 1.", 0.05, true);
		MEDICINE_Z_VIRUS_VOMIT_FORCE_MODIFIER = RegisterSettingFloat("Medicine.ZVirusVomitForceModifier", "Medicine", "Modifier responsible for the strength of vomiting. The higher value make more draining of water and energy the player will receive.", 0.5, true);
		
		RegisterRegion("Medicine", "Radiation settings");
		MEDICINE_RADIATION_ENABLED = RegisterSettingBool("Medicine.RadiationEnabled", "Medicine", "The parameter determines whether radiation sickness is enabled on the server or not.", true, true);
		MEDICINE_RADIATION_COMMON_DEC_PER_SEC = RegisterSettingFloat("Medicine.RadiationCommonDecPerSec", "Medicine", "The number of radiation agents the player loses every second without drugs.", 0.001, true);
		MEDICINE_RADIATION_MEDS_DEC_PER_SEC = RegisterSettingFloat("Medicine.RadiationMedsDecPerSec", "Medicine", "The number of radiation agents the player loses every second with drugs.", 0.003, true);
		MEDICINE_RADIATION_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.RadiationCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of zombie virus.", 1.5, true);
		MEDICINE_RADIATION_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.RadiationLightSymptomChance", "Medicine", "Chance to make light (level 2+) radiation symptoh. Value from 0 to 1.", 0.005, true);
		MEDICINE_RADIATION_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.RadiationHeavySymptomChance", "Medicine", "Chance to make heavy (level 3) radiation symptoh. Value from 0 to 1.", 0.004, true);
		MEDICINE_RADIATION_VOMIT_FORCE_MODIFIER = RegisterSettingFloat("Medicine.RadiationVomitForceModifier", "Medicine", "Modifier responsible for the strength of vomiting. The higher value make more draining of water and energy the player will receive.", 1.0, true);
		MEDICINE_RADIATION_TRANSFER_PER_SEC = RegisterSettingFloat("Medicine.RadiationTransferPerSec", "Medicine", "Determines the maximum number of rengens per second that will be converted from the player's radiation exposure to radiation sickness units. Default value is 1.0", 1.0, true);
		MEDICINE_RADIATION_TRANSFER_MOD = RegisterSettingFloat("Medicine.RadiationTransferMod", "Medicine", "Determines the conversion modifier for converting a single rengen accumulated in the player's body into one stage of radiation sickness. Default value is 0.0035 (~280 rentgents to take 1 lvl of radiation sickness).", 0.0035, true);
		MEDICINE_RADIATION_TRANSFER_GEAR = RegisterSettingFloat("Medicine.RadiationTransferFromGear", "Medicine", "Determines the conversion modifier for converting a single rengen accumulated in the player's equipment into the body. Default value is 1.0.", 1.0, true);
		
		RegisterRegion("Medicine", "Food poison settings");
		MEDICINE_POSION_ENABLED = RegisterSettingBool("Medicine.PosionEnabled", "Medicine", "The parameter determines whether food poison is enabled on the server or not.", true, true);
		MEDICINE_POISON_DEC_PER_SEC = RegisterSettingFloat("Medicine.PoisonDecPerSec", "Medicine", "The number of poison agents the player loses every second.", 0.003, true);
		MEDICINE_POISON_ANTIDOTE_HEAL_MULTIPLIER = RegisterSettingFloat("Medicine.PoisonAntidoteHealMultiplier", "Medicine", "A modifier that affects the strength of medicines against poisoning. Affects the lose force of poisonous agents from the body.", 1.0, true);
		MEDICINE_POISON_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.PoisonLightSymptomChance", "Medicine", "Chance to make light (level 1) poison symptoh. Value from 0 to 1.", 0.004, true);
		MEDICINE_POISON_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.PoisonHeavySymptomChance", "Medicine", "Chance to make heavy (level 2) poison symptoh. Value from 0 to 1.", 0.01, true);
		MEDICINE_POISON_CRITICAL_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.PoisonCriticalSymptomChance", "Medicine", "Chance to make critical (level 3) poison symptoh. Value from 0 to 1.", 0.05, true);
		MEDICINE_POISON_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.PoisonCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of poison.", 0.25, true);
		MEDICINE_POISON_VOMIT_FORCE_MODIFIER = RegisterSettingFloat("Medicine.PoisonVomitForceModifier", "Medicine", "Modifier responsible for the strength of vomiting. The higher value make more draining of water adn energy the player will receive.", 1.0, true);
		MEDICINE_POISON_TRANSFER_AGENTS_MODIFIER = RegisterSettingFloat("Medicine.PoisonTransferAgentsModifier", "Medicine", "A modifier responsible for converting classic agents into agents of the Terje medicine system.", 0.25, true);
		
		RegisterRegion("Medicine", "Biohazard (toxic poison) settings");
		MEDICINE_BIOHAZARD_ENABLED = RegisterSettingBool("Medicine.BiohazardEnabled", "Medicine", "The parameter determines whether biohazard is enabled on the server or not.", true, true);
		MEDICINE_BIOHAZARD_SKIN_IRRITATION = RegisterSettingBool("Medicine.BiohazardSkinIrritation", "Medicine", "Enables or disables the vanilla skin irritation symptom when player stay in a toxic area.", false, true);
		MEDICINE_BIOHAZARD_REQUIRED_ONLY_GAS_MASK = RegisterSettingBool("Medicine.BiohazardRequiredOnlyGasMask", "Medicine", "Enables or disables the behavior in which only a gas mask is needed to stay in a toxic zone without damage.", true, true);
		MEDICINE_BIOHAZARD_DEC_PER_SEC = RegisterSettingFloat("Medicine.BiohazardDecPerSec", "Medicine", "The number of biohazard agents the player loses every second.", 0.001, true);
		MEDICINE_BIOHAZARD_ANTIDOTE_HEAL_MULTIPLIER = RegisterSettingFloat("Medicine.BiohazardAntidoteHealMultiplier", "Medicine", "A modifier that affects the strength of medicines against biohazard poisoning. Affects the lose force of poisonous biohazard agents from the body.", 1.0, true);
		MEDICINE_BIOHAZARD_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.BiohazardSymptomChance", "Medicine", "Chance to make heavy (level 2+) biohazard symptoh. Value from 0 to 1.", 0.05, true);
		MEDICINE_BIOHAZARD_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.BiohazardCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of biohazard.", 0.35, true);
		MEDICINE_BIOHAZARD_VOMIT_FORCE_MODIFIER = RegisterSettingFloat("Medicine.BiohazardVomitForceModifier", "Medicine", "Modifier responsible for the strength of vomiting. The higher value make more draining of water adn energy the player will receive.", 2.5, true);
		MEDICINE_BIOHAZARD_TRANSFER_AGENTS_MODIFIER = RegisterSettingFloat("Medicine.BiohazardTransferAgentsModifier", "Medicine", "A modifier responsible for converting classic chemical agents into biohazard agents of the Terje medicine system.", 0.25, true);
		
		RegisterRegion("Medicine", "Rabies settings");
		MEDICINE_RABIES_ENABLED = RegisterSettingBool("Medicine.RabiesEnabled", "Medicine", "The parameter determines whether rabies is enabled on the server or not.", true, true);
		MEDICINE_RABIES_WOLF_INFECTED_CHANCE = RegisterSettingFloat("Medicine.RabiesWolfInfectedChance", "Medicine", "The chance of a wolf being infected with rabies (determined when the wolf is spawned). Default value is 0.25", 0.25, true);
		MEDICINE_RABIES_INC_PER_SEC = RegisterSettingFloat("Medicine.RabiesIncPerSec", "Medicine", "The number of rabies agents the player receives every second when infected.", 0.0001, true);
		MEDICINE_RABIES_DEC_PER_SEC = RegisterSettingFloat("Medicine.RabiesDecPerSec", "Medicine", "The number of rabies agents the player loses when has effect from antibiotics.", 0.001, true);
		MEDICINE_RABIES_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.RabiesCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of rabies.", 1.0, true);
		MEDICINE_RABIES_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.RabiesLightSymptomChance", "Medicine", "Chance to make light (level 1) rabies symptoh. Value from 0 to 1.", 0.025, true);
		MEDICINE_RABIES_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.RabiesHeavySymptomChance", "Medicine", "Chance to make heavy (level 2) rabies symptoh. Value from 0 to 1.", 0.1, true);
		MEDICINE_RABIES_CRITICAL_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.RabiesCriticalSymptomChance", "Medicine", "Chance to make critical (level 3) rabies symptoh. Value from 0 to 1.", 0.1, true);
		MEDICINE_RABIES_BODY_TEMPERATURE_MODIFIER = RegisterSettingFloat("Medicine.RabiesBodyTemperatureModifier", "Medicine", "A modifier that increases body temperature multiplied by the stage of the disease.", 25, true);
		
		RegisterRegion("Medicine", "Influenza (Cold and pneumonia) settings");
		MEDICINE_INFLUENZA_ENABLED = RegisterSettingBool("Medicine.InfluenzaEnabled", "Medicine", "The parameter determines whether influenza is enabled on the server or not.", true, true);
		MEDICINE_INFLUENZA_INC_PER_SEC = RegisterSettingFloat("Medicine.InfluenzaIncPerSec", "Medicine", "The number of influenza agents the player receives every second when infected.", 0.0006, true);
		MEDICINE_INFLUENZA_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.InfluenzaCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during terminal stage of influenza.", 0.75, true);
		MEDICINE_INFLUENZA_DEC_PER_SEC = RegisterSettingFloat("Medicine.InfluenzaDecPerSec", "Medicine", "The number of influenza agents the player loses when has effect from antibiotics.", 0.005, true);
		MEDICINE_INFLUENZA_LIGHT_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.InfluenzaLightSymptomChance", "Medicine", "Chance to make light (level 1) influenza symptoh. Value from 0 to 1.", 0.02, true);
		MEDICINE_INFLUENZA_HEAVY_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.InfluenzaHeavySymptomChance", "Medicine", "Chance to make heavy (level 2) influenza symptoh. Value from 0 to 1.", 0.02, true);
		MEDICINE_INFLUENZA_CRITICAL_SYMPTOM_CHANCE = RegisterSettingFloat("Medicine.InfluenzaCriticalSymptomChance", "Medicine", "Chance to make critical (level 3) influenza symptoh. Value from 0 to 1.", 0.05, true);
		MEDICINE_INFLUENZA_BODY_TEMPERATURE_MODIFIER = RegisterSettingFloat("Medicine.InfluenzaBodyTemperatureModifier", "Medicine", "A modifier that increases body temperature multiplied by the stage of the disease.", 20, true);
		MEDICINE_INFLUENZA_DEFAULT_IMMUNITY_STRENGTH = RegisterSettingFloat("Medicine.InfluenzaDefaultImmunityStrength", "Medicine", "A modifier responsible for the strength of the player’s immunity to cure influenza. Value from 0 to 1.", 0.2, true);
		MEDICINE_INFLUENZA_TRANSFER_AGENTS_MODIFIER = RegisterSettingFloat("Medicine.InfluenzaTransferAgentsModifier", "Medicine", "A modifier responsible for converting classic influenza agents into agents of the Terje medicine system.", 0.002, true);
		MEDICINE_INFLUENZA_IMMUNITY_HEAL_THRESHOLD = RegisterSettingFloat("Medicine.InfluenzaImmunityHealThreshold", "Medicine", "The value of the influenza to which the player can be cured without medicine using his immunity and staying in warm place. Above this value, influenza can only be treated with antibiotics.", 1.25, true);
		MEDICINE_INFLUENZA_TEMPERATURE_WARN_MODIFIER = RegisterSettingFloat("Medicine.InfluenzaTemperatureWarnModifier", "Medicine", "Modifier for the evolve of the disease when the player’s temperature drops below the warning mark (light-blue thermometer).", 0.1, true);
		MEDICINE_INFLUENZA_TEMPERATURE_CRIT_MODIFIER = RegisterSettingFloat("Medicine.InfluenzaTemperatureCritModifier", "Medicine", "Modifier for the evolve of the disease when the player’s temperature drops below the critical mark (blue thermometer).", 0.5, true);
		MEDICINE_INFLUENZA_TEMPERATURE_EMPTY_MODIFIER = RegisterSettingFloat("Medicine.InfluenzaTemperatureEmptyModifier", "Medicine", "Modifier for the evolve of the disease when the player’s temperature drops below the empty mark (empty thermometer).", 1.0, true);
		
		RegisterRegion("Medicine", "Overdose settings");
		MEDICINE_OVERDOSE_ENABLED = RegisterSettingBool("Medicine.OverdoseEnabled", "Medicine", "The parameter determines whether overdose is enabled on the server or not.", true, true);
		MEDICINE_OVERDOSE_DEC_PER_SEC = RegisterSettingFloat("Medicine.OverdoseDecPerSec", "Medicine", "The number of overdose agents the player loses every second.", 0.0015, true);
		MEDICINE_OVERDOSE_UNCONSCIOUS_CHANCE = RegisterSettingFloat("Medicine.OverdoseUnconsciousChance", "Medicine", "Chance to fall unconscious at level 2 overdose. Value from 0 to 1.", 0.025, true);
		MEDICINE_OVERDOSE_CRITICAL_DMG_MULTIPLIER = RegisterSettingFloat("Medicine.OverdoseCriticalDmgMultiplier", "Medicine", "Damage modifier received by a player during level 3 overdose.", 2.5, true);
		
		RegisterRegion("Medicine", "Contusion (brain physical damage) settings");
		MEDICINE_CONTUSION_ENABLED = RegisterSettingBool("Medicine.ContusionEnabled", "Medicine", "The parameter determines whether contusion is enabled on the server or not.", true, true);
		MEDICINE_CONTUSION_DEC_PER_SEC = RegisterSettingFloat("Medicine.ContusionDecPerSec", "Medicine", "The number of contusion points the player loses every second.", 0.002, true);
		MEDICINE_CONTUSION_UNCONSCIOUS_CHANCE = RegisterSettingFloat("Medicine.ContusionUnconsciousChance", "Medicine", "Chance to fall unconscious with contusion. Value from 0 to 1.", 0.005, true);
		MEDICINE_CONTUSION_HEAL_MODIFIER = RegisterSettingFloat("Medicine.ContusionHealModifier", "Medicine", "Modifier responsible for the strength of contussion heal with meds.", 5.0, true);
		
		RegisterRegion("Medicine", "Hematomas (bruises) settings");
		MEDICINE_HEMATOMAS_ENABLED = RegisterSettingBool("Medicine.HematomasEnabled", "Medicine", "The parameter determines whether hematomas is enabled on the server or not.", true, true);
		MEDICINE_HEMATOMAS_HEAL_COMMON_MODIFIER = RegisterSettingFloat("Medicine.HematomasHealCommonModifier", "Medicine", "Modifier responsible for the strength of hematomas (bruises) heal without meds.", 0.003, true);
		MEDICINE_HEMATOMAS_HEAL_MEDS_MODIFIER = RegisterSettingFloat("Medicine.HematomasHealMedsModifier", "Medicine", "Modifier responsible for the strength of hematomas (bruises) heal with meds.", 0.01, true);
		MEDICINE_HEMATOMAS_CRITICAL_COUNT = RegisterSettingFloat("Medicine.HematomasCriticalCount", "Medicine", "The number of hematomas, starting from which the player begins to lose health.", 3, true);
		MEDICINE_HEMATOMAS_CRITICAL_DAMAGE = RegisterSettingFloat("Medicine.HematomasCriticalDamage", "Medicine", "The damage the player receives for each hematoma above the HematomasCriticalCount threshold.", 0.02, true);
		
		RegisterRegion("Medicine", "Melee damage settings");
		MEDICINE_MELEE_DAMMAGE_PLAYER_IN_BLOCK = RegisterSettingFloat("Medicine.MeleeDammagePlayerInBlock", "Medicine", "Chance of receiving damage from melee attack when the player stay in block. Value from 0 to 1.", 0.1, true);
		MEDICINE_MELEE_DAMMAGE_NO_STAMINA = RegisterSettingBool("Medicine.MeleeDammageNoStamina", "Medicine", "Melee attack make damage to the player in the block if the player has no stamina.", true, true);
		MEDICINE_MELEE_DAMMAGE_CONTUSION_CHANCE = RegisterSettingFloat("Medicine.MeleeDammageContusionChance", "Medicine", "Chance of receiving contusion from melee attack when the player take dammage to the head. Value from 0 to 1.", 0.5, true);
		MEDICINE_MELEE_DAMMAGE_STUB_WOUND_CHANCE = RegisterSettingFloat("Medicine.MeleeDammageStubWoundChance", "Medicine", "Chance of receiving stub wound from sharp melee attack when the player take dammage. Value from 0 to 1.", 0.8, true);
		MEDICINE_MELEE_DAMMAGE_VISCERA_CHANCE = RegisterSettingFloat("Medicine.MeleeDammageVisceraChance", "Medicine", "Chance of receiving viscera wound from sharp melee attack when the player take dammage in torso. Value from 0 to 1.", 0.1, true);
		MEDICINE_MELEE_DAMMAGE_SEPSIS_CHANCE = RegisterSettingFloat("Medicine.MeleeDammageSepsisChance", "Medicine", "Chance of receiving sepsis infection from sharp melee attack when the player take dammage. Value from 0 to 1.", 0.05, true);
		MEDICINE_MELEE_DAMMAGE_HEMATOMA_CHANCE = RegisterSettingFloat("Medicine.MeleeDammageHematomaChance", "Medicine", "Chance of receiving hematoma from melee attack when the player take dammage. Value from 0 to 1.", 0.8, true);
		MEDICINE_MELEE_DAMMAGE_PAIN_MIN = RegisterSettingFloat("Medicine.MeleeDammagePainMin", "Medicine", "The minimum amount of pain a player will receive when hited by melee. A random value between the minimum and maximum values will be selected.", 0.1, true);
		MEDICINE_MELEE_DAMMAGE_PAIN_MAX = RegisterSettingFloat("Medicine.MeleeDammagePainMax", "Medicine", "The maximum amount of pain a player will receive when hited by a melee. A random value between the minimum and maximum values will be selected.", 0.5, true);
		MEDICINE_MELEE_DAMMAGE_PAIN_STUB = RegisterSettingFloat("Medicine.MeleeDammagePainStub", "Medicine", "The amount of pain a player will receive when hited by a melee and received stub wound.", 2.5, true);
		
		RegisterRegion("Medicine", "Firearm (projectile) settings");
		MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_SPEED_MOD = RegisterSettingFloat("Medicine.FirearmBalliscticCalculatorSpeedMod", "Medicine", "Ballistic calculator modifier responsible for the effect of bullet speed on armor penetration. A higher value provides a higher chance to penetrate armor.", 1.0, true);
		MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_CALIBER_MOD = RegisterSettingFloat("Medicine.FirearmBalliscticCalculatorCaliberMod", "Medicine", "Ballistic calculator modifier responsible for the effect of bullet caliber on armor penetration. A higher value provides a higher chance to penetrate armor.", 1.0, true);
		MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_WEIGHT_MOD = RegisterSettingFloat("Medicine.FirearmBalliscticCalculatorWeightMod", "Medicine", "Ballistic calculator modifier responsible for the effect of bullet weight on armor penetration. A higher value provides a higher chance to penetrate armor.", 1.0, true);
		MEDICINE_FIREARM_BALLISCTIC_CALCULATOR_A_P_MOD = RegisterSettingFloat("Medicine.FirearmBalliscticCalculatorAPMod", "Medicine", "Ballistic calculator modifier responsible for the AP (armor penetration) effect on armor penetration. A higher value provides a higher chance to penetrate armor.", 1.0, true);
		MEDICINE_FIREARM_ARMOR_MODIFIER = RegisterSettingFloat("Medicine.FirearmArmorModifier", "Medicine", "Modifier used in the ballistic calculator to calculate armor penetration.", 1.0, true);
		MEDICINE_FIREARM_DAMMAGE_CONTUSION_CHANCE = RegisterSettingFloat("Medicine.FirearmDammageContusionChance", "Medicine", "Chance of receiving contusion from firearm when the player take dammage to the head. Value from 0 to 1.", 1.0, true);
		MEDICINE_FIREARM_DAMMAGE_VISCERA_CHANCE = RegisterSettingFloat("Medicine.FirearmDammageVisceraChance", "Medicine", "Chance of receiving viscera wound from firearm when the player take dammage in torso. Value from 0 to 1.", 0.2, true);
		MEDICINE_FIREARM_BULLET_THROUGH_CHANCE = RegisterSettingFloat("Medicine.FirearmBulletThroughChance", "Medicine", "Chance of a bullet through and through when the player takes damage from a firearm. Value from 0 to 1.", 0.4, true);
		MEDICINE_FIREARM_DAMMAGE_SEPSIS_CHANCE = RegisterSettingFloat("Medicine.FirearmDammageSepsisChance", "Medicine", "Chance of receiving sepsis infection from firearm attack when the player take dammage. Value from 0 to 1.", 0.05, true);	
		MEDICINE_FIREARM_DAMMAGE_PAIN_STUB = RegisterSettingFloat("Medicine.FirearmDammagePainStub", "Medicine", "The amount of pain a player will receive when hited by a firearm and received stub wound.", 2.2, true);
		MEDICINE_FIREARM_DAMMAGE_PAIN_BULLET = RegisterSettingFloat("Medicine.FirearmDammagePainBullet", "Medicine", "The amount of pain a player will receive when hited by a firearm and received bullet wound.", 2.8, true);
		MEDICINE_FIREARM_DAMMAGE_PAIN_STOPPED = RegisterSettingFloat("Medicine.FirearmDammagePainStopped", "Medicine", "The amount of pain a player will receive when hited by a firearm and bullet stopped by armor.", 1.1, true);

		RegisterRegion("Medicine", "Zombie AI settings");
		MEDICINE_ZOMBIE_ATTACK_MIND_DEGRADATION_VALUE = RegisterSettingFloat("Medicine.ZombieAttackMindDegradationValue", "Medicine", "The amount of mind that a player will lose per second during a fight with a zombie.", 0.2, true);
		MEDICINE_ZOMBIE_ATTACK_MIND_DEGRADATION_TIME = RegisterSettingFloat("Medicine.ZombieAttackMindDegradationTime", "Medicine", "Time in seconds during which the player will continue to lose his mind after a fight.", 10, true);
		MEDICINE_ZOMBIE_DAMMAGE_PLAYER_IN_BLOCK = RegisterSettingFloat("Medicine.ZombieDammagePlayerInBlock", "Medicine", "Chance of receiving damage from zombies when the player stay in block. Value from 0 to 1.", 0.0, true);
		MEDICINE_ZOMBIE_DAMMAGE_NO_STAMINA = RegisterSettingBool("Medicine.ZombieDammageNoStamina", "Medicine", "Zombies make damage to the player in the block if the player has no stamina.", true, true);
		MEDICINE_ZOMBIE_DAMMAGE_HEMATOMA_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageHematomaChance", "Medicine", "Chance of receiving from zombie a hematoma when attack is not blocked. Value from 0 to 1.", 0.5, true);
		MEDICINE_ZOMBIE_DAMMAGE_BLEED_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageBleedChance", "Medicine", "Chance of receiving from zombie a bleeding when attack is not blocked. Value from 0 to 1.", 0.05, true);
		MEDICINE_ZOMBIE_DAMMAGE_CONTUSION_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageContusionChance", "Medicine", "Chance of receiving from zombie a contusion when attack is not blocked in the head. Value from 0 to 1.", 0.3, true);
		MEDICINE_ZOMBIE_DAMMAGE_STUB_WOUND_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageStubWoundChance", "Medicine", "Chance of receiving from zombie a stub wound when attack is not blocked. Value from 0 to 1.", 0.01, true);	
		MEDICINE_ZOMBIE_DAMMAGE_HEMATOMA_VIRUS_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageHematomaVirusChance", "Medicine", "Chance of receiving zombie virus from hematoma damage. Value from 0 to 1.", 0.0, true);
		MEDICINE_ZOMBIE_DAMMAGE_BLEED_VIRUS_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageBleedVirusChance", "Medicine", "Chance of receiving zombie virus from bleeding damage. Value from 0 to 1.", 0.25, true);
		MEDICINE_ZOMBIE_DAMMAGE_STUB_WOUND_VIRUS_CHANCE = RegisterSettingFloat("Medicine.ZombieDammageStubWoundVirusChance", "Medicine", "Chance of receiving zombie virus from stub wound damage. Value from 0 to 1.", 0.8, true);
		MEDICINE_ZOMBIE_DAMMAGE_PAIN_MIN = RegisterSettingFloat("Medicine.ZombieDammagePainMin", "Medicine", "The minimum amount of pain a player will receive when hited by a zombie. A random value between the minimum and maximum values will be selected.", 0.1, true);
		MEDICINE_ZOMBIE_DAMMAGE_PAIN_MAX = RegisterSettingFloat("Medicine.ZombieDammagePainMax", "Medicine", "The maximum amount of pain a player will receive when hited by a zombie. A random value between the minimum and maximum values will be selected.", 0.4, true);
		MEDICINE_ZOMBIE_DAMMAGE_PAIN_STUB = RegisterSettingFloat("Medicine.ZombieDammagePainStub", "Medicine", "The amount of pain a player will receive when hited by a zombie and received stub wound.", 2.2, true);

		RegisterRegion("Medicine", "ImmunitySkill");
		MEDICINE_IMMUNITY_BIOHAZARD_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityBiohazardExpGain", "Medicine", "Sets the value of experience points that the player will gain after the biohazard disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 100.", 100, true);
		MEDICINE_IMMUNITY_CONTUSION_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityContusionExpGain", "Medicine", "Sets the value of experience points that the player will gain after the contusion disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 50.", 50, true);
		MEDICINE_IMMUNITY_HEMATOMA_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityHematomaExpGain", "Medicine", "Sets the value of experience points that the player will gain after the hematoma is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 10.", 10, true);
		MEDICINE_IMMUNITY_INFLUENZA_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityInfluenzaExpGain", "Medicine", "Sets the value of experience points that the player will gain after the influenza disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 120.", 120, true);
		MEDICINE_IMMUNITY_PAIN_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityPainExpGain", "Medicine", "Sets the value of experience points that the player will gain after the pain is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 25.", 25, true);
		MEDICINE_IMMUNITY_POISON_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityPoisonExpGain", "Medicine", "Sets the value of experience points that the player will gain after the poisoning disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 80.", 80, true);
		MEDICINE_IMMUNITY_RADIATION_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityRadiationExpGain", "Medicine", "Sets the value of experience points that the player will gain after the radiation disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 100.", 100, true);
		MEDICINE_IMMUNITY_SEPSIS_EXP_GAIN = RegisterSettingInt("Medicine.ImmunitySepsisExpGain", "Medicine", "Sets the value of experience points that the player will gain after the sepsis disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 100.", 100, true);
		MEDICINE_IMMUNITY_ZOMBIE_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityZombieExpGain", "Medicine", "Sets the value of experience points that the player will gain after the zombie disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 250.", 250, true);
		MEDICINE_IMMUNITY_RABIES_EXP_GAIN = RegisterSettingInt("Medicine.ImmunityRabiesExpGain", "Medicine", "Sets the value of experience points that the player will gain after the rabies disease is completely cured. This parameter is also affected by 'ExperienceGainModifier'. Default value is 150.", 150, true);

		RegisterRegion("Medicine", "MedicineSkill");
		MEDICINE_MEDICINE_BANDAGE_EXP_GAIN = RegisterSettingInt("Medicine.MedicineBandageExpGain", "Medicine", "Sets the value of experience points that the player will gain after the bandaging. This parameter is also affected by 'ExperienceGainModifier'. Default value is 50.", 50, true);
		MEDICINE_MEDICINE_STUB_SURGERY_EXP_GAIN = RegisterSettingInt("Medicine.MedicineStubSurgeryExpGain", "Medicine", "Sets the value of experience points that the player will gain after the surgery of the stub wound. This parameter is also affected by 'ExperienceGainModifier'. Default value is 500.", 500, true);
		MEDICINE_MEDICINE_BULLET_SURGERY_EXP_GAIN = RegisterSettingInt("Medicine.MedicineBulletSurgeryExpGain", "Medicine", "Sets the value of experience points that the player will gain after the surgery of the bullet wound. This parameter is also affected by 'ExperienceGainModifier'. Default value is 750.", 750, true);
		MEDICINE_MEDICINE_VISCERA_SURGERY_EXP_GAIN = RegisterSettingInt("Medicine.MedicineVisceraSurgeryExpGain", "Medicine", "Sets the value of experience points that the player will gain after the surgery of the viscera wound. This parameter is also affected by 'ExperienceGainModifier'. Default value is 1000.", 1000, true);
		
		RegisterRegion("Medicine", "TerjeScriptableAreas");
		MEDICINE_PSIONIC_AREAS_POWER_MOD = RegisterSettingFloat("Medicine.PsionicAreasPowerMod", "Medicine", "Power modifier for all psionic areas. Default value is 1.0", 1.0, true);
		MEDICINE_RADIOACTIVE_AREAS_POWER_MOD = RegisterSettingFloat("Medicine.RadioactiveAreasPowerMod", "Medicine", "Power modifier for all radioactive areas. Default value is 1.0", 1.0, true);
		MEDICINE_RADIATION_DAMAGE_ZOMBIES = RegisterSettingBool("Medicine.RadioationDamageZombies", "Medicine", "Determines whether radiation do damage to zombies. Default values is false.", false, true);
		MEDICINE_RADIATION_DAMAGE_ANIMALS = RegisterSettingBool("Medicine.RadioationDamageAnimals", "Medicine", "Determines whether radiation do damage to animals. Default values is true.", true, true);
		MEDICINE_RADIATION_DO_ITEMS_ACCUMULATE = RegisterSettingBool("Medicine.RadioationDoItemsAccumulate", "Medicine", "Determines whether radiation will accumulate by items inside the radioactive area. Default values is true.", true, true);
		MEDICINE_RADIATION_DO_VEHICLES_ACCUMULATE = RegisterSettingBool("Medicine.RadioationDoVehiclesAccumulate", "Medicine", "Determines whether radiation will accumulate by vehicles inside the radioactive area. Default values is true.", true, true);
		MEDICINE_RADIATION_TRANSFER_WITH_PARENT = RegisterSettingBool("Medicine.RadioationTransferWithParent", "Medicine", "Determines whether radiation can be transfered between object to its parent. Default values is true.", true, true);
		MEDICINE_RADIATION_ITEM_LOSE_PER_SEC = RegisterSettingFloat("Medicine.RadiationItemLosePerSec", "Medicine", "How many rentgens of radiation accumulated in the item will it lose per second.", 0.1, true);
	}
};
